config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
	
  resources :stories, only:[:index,:show] , :controller => 'stories' do 
    resources :comments, only:[:create,:destroy], :controller => 'story_comments'
    member do 
      post :like ,:controller => 'stories'
      post :unlike,:controller => 'stories'
    end 

  end

  resources :projects, only:[:index,:show] do #前台只能看index和show頁面
		resources :donations, only:[:show,:new,:create], :controller => 'project_donations' do 
      member do
        post :checkout_pay2go
      end
    end
	end

	root :to =>'stories#index', :controller => 'stories'

  resources :tags, only:[:show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  post 'pay2go/return'
  post 'pay2go/notify'

	namespace :admin do
    resources :stories ,:controller => 'stories' do 
      collection do
        get :home ,:controller => 'stories'
      end
    end
  	resources :projects do #後台CRUD都可
      resources :donation, only:[:index], :controller => 'project_donations'
      resource :report, :controller => 'project_reports'
    end
    
  	resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :tags
	end

  namespace :account do
    resources :stories do 
      collection do
        get :liked
      end
    end
    resources :project_donations
  end

	 #API routes path
  namespace :api, defaults:{ format: :json }do
    namespace :v1 do
      #devise_for :users
      post '/login' => 'auth#login'
      post '/logout' => 'auth#logout'
      resources :users
    end
  end 
  
  

  get '/aboutus', to: 'home#about', :controller => 'home'
  get '/contactus', to: 'home#contact', :controller => 'home'


end

app/models/project.rb
class Project < ApplicationRecord
	has_many :photos, dependent: :destroy
	has_many :donations 
	belongs_to :story
	validates_presence_of :due_date,:name, :content
	validates :total_amount, numericality: { only_integer: true }
	accepts_nested_attributes_for :photos,:allow_destroy => true, :reject_if => :all_blank
  has_one :report

	def story_title
		self.story.title
	end

	def story_content
		self.story.content
	end

	def progress 
		(self.donation_amount.to_f/self.total_amount)*100
	end
	
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_admin
	before_action :find_project, only:[:show,:edit, :update, :destroy]
	layout "admin"

	def index 
		@projects = Project.all
	end

	def show 
		
	end

	def new
		@project = Project.new
		@stories = Story.where(need_project: "yes")
		5.times {@photos = @project.photos.build}
		

	end

	def create
		@project = Project.new(project_params)	
		@stories = Story.where(need_project: "yes")
		if @project.save
			respond_to do |format|
				  format.html { redirect_to admin_project_path(@project)}
				  format.js	
				  
			end		
		else 
			5.times {@photos = @project.photos.build}
			render :new
		end
	end

	def edit 
		@stories = Story.where(need_project: true)
		a = @project.photos.count
		b = 5-a
		b.times {@photos = @project.photos.build}
	end

	def update
		if @project.update(project_params)		
			
			respond_to do |format|
				  format.html { redirect_to admin_project_path(@project)}
				  format.js
			end		
		else 
			render :edit
		end
	end


	def destroy 
		@project.destroy
		redirect_to admin_projects_path
	end
    


	protected 
	def check_admin 
		unless current_user.role == "admin"
			raise ActiveRecord::RecordNotFound			
		end
	end
	def find_project
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:due_date,:name,:content,
			                            :is_public,:total_amount, 
			                            :story_id,
			                            :photos_attributes => [:id, :image, :_destroy],
			                            :report_attributes => [:id, :name, :_destroy] 
			                            )
	end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@page_title = "專案"
		@projects = Project.where(:is_public => true)
		
	end

	def show 
		@page_title = "專案細節"
		@project = Project.find(params[:id])
		@days = (@project.due_date - Date.today).to_i
		@people = @project.donations.count
		@photos = @project.photos
		@photos_count = @photos.count
		@progress = @project.progress.round(0)
	end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper


end

app/views/admin/projects/_form.html.erb
<% if @project.errors.present?%>
  <ul>
        <% @project.errors.each do |error, message|%>
          <li> <%= "#{error.capitalize}  #{message}" %></li>
        <% end %>
  </ul>
<% end%>


<div class="container">

	<%= form_for ([:admin, @project])  do |f| %>
		<div class="form_group">
			<%= f.label :story_id %>
			<% @stories.each do |s| %>
    		<%= f.radio_button :story_id, s.id%><%= s.title%>
			<% end %>	
		</div>
		<div class="form_group">
			<%= f.label :name, "專案名稱:" %><br>
			<%= f.text_field :name %><br>
		</div>

		<div class="form_group">
			<%= f.label :content, "專案內容:" %><br>
			<%= f.text_area :content ,class:"editable" %><br>
		</div>
		
		
		<div class="input-group">
			<img id='img-upload'/>
			<ol>
				<%= f.fields_for :photos do |p|  %>

					<li><%= p.label :image , "專案照片:" %>
					<%= p.file_field :image , class:"imgInp" %></li>

				<% end %>
			</ol>
		</div>
		
		<div class="form_group">
			<%= f.label :due_date, "募款到期日:" %><br>
			<%= f.date_select :due_date %><br>
		</div>

		<div class="form_group">
			<%= f.label :total_amount, "預計募款總金額:" %><br>
			<%= f.text_field :total_amount %><br>
		</div>
		
		<div class="form_group">
			<%= f.radio_button :is_public,true,:value => true %>
			<%= f.label :is_public, "公布"%>
			<%= f.radio_button :is_public,false,:value => false %>		
			<%= f.label :is_public, "尚未公布"%>
		</div>
		

		<%= f.submit class:"btn btn-default" %>

		
	<% end %>
</div>

<script>
	$(document).ready( function() {
    	$(document).on('change', '.btn-file :file', function() {
		var input = $(this),
			label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
		input.trigger('fileselect', [label]);
		});

		$('.btn-file :file').on('fileselect', function(event, label) {
		    
		    var input = $(this).parents('.input-group').find(':text'),
		        log = label;
		    
		    if( input.length ) {
		        input.val(log);
		    } else {
		        if( log ) alert(log);
		    }
	    
		});
		function readURL(input) {
		    if (input.files && input.files[0]) {
		        var reader = new FileReader();
		        
		        reader.onload = function (e) {
		            $('#img-upload').attr('src', e.target.result);
		        }
		        
		        reader.readAsDataURL(input.files[0]);
		    }
		}

		$(".imgInp").change(function(){
		    readURL(this);
		}); 	
	});
</script>

app/views/admin/projects/edit.html.erb
<div class="container">
  <h1>後台編輯專案</h1>
</div>

<div class="container">
	<%= render :partial => "form" %>
</div>

app/views/admin/projects/index.html.erb
<div class="container">
	<h1 class="text-center">所有專案</h1>
</div>


<div class="container text-center">
	<%= link_to "新增專案", new_admin_project_path,class:"btn btn-default" %>
</div>

<div class="container">
	<% @projects.each do |p| %>
	<div class="col-md-6 text-center">
		<table class="table table-bordered">
			<tr>
				<td>
					專案名稱:<%= p.name %>
				</td>
			</tr>
			<tr>
				<td>
					是否公開:<%= p.is_public %>
				</td>
			</tr>
			<tr>
				<td>
					<%= link_to "Detail", admin_project_path(p) %>
				</td>
			</tr>
			<tr>
				<td>
				  <% if p.report %>
            <%= link_to "查看成效報告", admin_project_report_path(p),class:"btn-default"%>
			    <% else %>
			      <%= link_to "新增成效報告", new_admin_project_report_path(p) ,class:"btn-default"%>
			    <% end %>
				</td>
			</tr>

		</table>
	</div>
	<% end %>

</div>

app/views/admin/projects/new.html.erb
<div class="container">
  <h1>後台新增專案</h1>
</div>
<div class="container">
	<%= render :partial => "form" %>
</div>

app/views/admin/projects/show.html.erb
<section>
  <div class="container text-center ">
	  <h1><%= @project.name %>專案</h1>
	  <hr class="short" style="border-top: 4px double #8c8b8b;
	text-align: center;">
	</div>
	<div class="container text-center">
    <%= link_to "刪除", admin_project_path(@project) ,method: :delete, data:{ confirm: "Are you sure?"} ,class:"btn btn-default"%>
    <%= link_to "編輯", edit_admin_project_path(@project) ,class:"btn btn-default"%>
    <%= link_to "查看募資細節",admin_project_donation_index_url(@project),class:"btn btn-default" %>

    <% if @project.report %>
      <%= link_to "查看成效報告", admin_project_report_path(@project),class:"btn btn-default"%>
    <% else %>
       <%= link_to "新增成效報告", new_admin_project_report_path(@project) ,class:"btn btn-default"%>
    <% end %>	
    <%= link_to "返回專案列表", admin_projects_path ,class:"btn btn-default"%> 
  </div>
	<div class="container ">
	  <div class="row">

      <div class="col-sm-12">
	    	<h2>細節</h2>  
	    	<hr class="short" style="border-top: 1px dotted #8c8b8b;">
	    	<ul>   
          <p><i class="fa fa-asterisk" aria-hidden="true">故事標題：</i><%= @project.story_title %> </p>
	        <p><i class="fa fa-asterisk" aria-hidden="true">到期日：</i> <%= @project.due_date %> </p>
	        <p><i class="fa fa-asterisk" aria-hidden="true">募資總金額：</i> <%= @project.total_amount %> </p>
	        <p><i class="fa fa-asterisk" aria-hidden="true">已募得金額：</i> <%= @project.donation_amount %> </p>
				</ul> 
	    </div>

	    <div class="col-sm-12">
        <h2>專案照片集</h2>
        <hr class="short" style="border-top: 1px dotted #8c8b8b;">
        <% @project.photos.each do|p| %>
	        <%= link_to image_tag(p.image.url(:medium)) ,class:"img-responsive" %>
        <% end %>
      </div>

	    <div class="col-sm-12">
        <div class="container " style="height:auto;">
          <h2>內容:</h2><%= sanitize(@project.content) %>
          <hr class="short" style="border-top: 1px dotted #8c8b8b;">
        </div>
	    </div>    
	  </div>
	     
	</div>
</section>