config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
	
  resources :stories, only:[:index,:show] , :controller => 'stories' do 
    resources :comments, only:[:create,:destroy], :controller => 'story_comments'
    member do 
      post :like ,:controller => 'stories'
      post :unlike,:controller => 'stories'
    end 

  end

  resources :projects, only:[:index,:show] do #前台只能看index和show頁面
		resources :donations, only:[:show,:new,:create], :controller => 'project_donations' do 
      member do
        post :checkout_pay2go
      end
    end
	end

	root :to =>'stories#index', :controller => 'stories'

  resources :tags, only:[:show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  post 'pay2go/return'
  post 'pay2go/notify'

	namespace :admin do
    resources :stories ,:controller => 'stories' do 
      collection do
        get :home ,:controller => 'stories'
      end
    end
  	resources :projects do #後台CRUD都可
      resources :donation, only:[:index], :controller => 'project_donations'
      resource :report, :controller => 'project_reports'
    end
    
  	resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :tags
	end

  namespace :account do
    resources :stories do 
      collection do
        get :liked
      end
    end
    resources :project_donations
  end

	 #API routes path
  namespace :api, defaults:{ format: :json }do
    namespace :v1 do
      #devise_for :users
      post '/login' => 'auth#login'
      post '/logout' => 'auth#logout'
      resources :users
    end
  end 
  
  

  get '/aboutus', to: 'home#about', :controller => 'home'
  get '/contactus', to: 'home#contact', :controller => 'home'


end

app/models/project.rb
class Project < ApplicationRecord
	has_many :photos, dependent: :destroy
	has_many :donations 
	belongs_to :story
	validates_presence_of :due_date,:name, :content
	validates :total_amount, numericality: { only_integer: true }
	accepts_nested_attributes_for :photos,:allow_destroy => true, :reject_if => :all_blank
  has_one :report

	def story_title
		self.story.title
	end

	def story_content
		self.story.content
	end

	def progress 
		(self.donation_amount.to_f/self.total_amount)*100
	end
	
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_admin
	before_action :find_project, only:[:show,:edit, :update, :destroy]
	layout "admin"

	def index 
		@projects = Project.all
	end

	def show 
		
	end

	def new
		@project = Project.new
		@stories = Story.where(need_project: "yes")
		5.times {@photos = @project.photos.build}
		

	end

	def create
		@project = Project.new(project_params)	
		@stories = Story.where(need_project: "yes")
		if @project.save
			respond_to do |format|
				  format.html { redirect_to admin_project_path(@project)}
				  format.js	
				  
			end		
		else 
			5.times {@photos = @project.photos.build}
			render :new
		end
	end

	def edit 
		@stories = Story.where(need_project: true)
		a = @project.photos.count
		b = 5-a
		b.times {@photos = @project.photos.build}
	end

	def update
		if @project.update(project_params)		
			
			respond_to do |format|
				  format.html { redirect_to admin_project_path(@project)}
				  format.js
			end		
		else 
			render :edit
		end
	end


	def destroy 
		@project.destroy
		redirect_to admin_projects_path
	end
    


	protected 
	def check_admin 
		unless current_user.role == "admin"
			raise ActiveRecord::RecordNotFound			
		end
	end
	def find_project
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:due_date,:name,:content,
			                            :is_public,:total_amount, 
			                            :story_id,
			                            :photos_attributes => [:id, :image, :_destroy],
			                            :report_attributes => [:id, :name, :_destroy] 
			                            )
	end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@page_title = "專案"
		@projects = Project.where(:is_public => true)
		
	end

	def show 
		@page_title = "專案細節"
		@project = Project.find(params[:id])
		@days = (@project.due_date - Date.today).to_i
		@people = @project.donations.count
		@photos = @project.photos
		@photos_count = @photos.count
		@progress = @project.progress.round(0)
	end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper


end

app/views/projects/index.html.erb
<div class="contaienr text-center">
	<%= image_tag "donation.png" %>
	<h1>募資專案</h1>
	<p>每個人的一點心力就能匯聚成眾大的公益力量，和我們ㄧ起行動!</p> 
	
</div>

<div class="container text-center">
<div class="container">
<row>
<% @projects.each do |p| %>
	<div class="col-md-6  table-bordered">
	<div class="col-md-12 text-center thead-inverse ">
		<h3 ><%=truncate(p.name, length: 20)%></strong></h3>	<hr>
	</div>
	<div class="col-md-12" >
		<%= link_to image_tag(p.photos.first.image.url,class:"top ")  %>
	</div>					
	<div class="col-md-12 text-center">
		<% @people = p.donations.count %>	
		<i class="fa fa-users" aria-hidden="true">目前參與人數: <%= @people %></i>
		<br><br>
		<i class="fa fa-spinner" aria-hidden="true">目前進度：</i> 
			<% @progress = p.progress.round(0) %> <br><br>

		<div class="progress">
	  	<div class="progress-bar pb" role="gressbar" style="width: <%= @progress %>%" aria-valuenow="<% @progress %>" aria-valuemin="0" aria-valuemax="100"><%= @progress %> %</div>
	  </div>
		
		<%= link_to "查看", project_path(p),class:"btn-2nd" %>	<br><br>	
	</div>
	</div>

	<% end %>			
</row>
</div>
</div>
<style>
	.container{
		margin-top: 20px;
	}
	.top{
		height: 250px;
	}
</style>

<script>
	$('.pb').css({
    'background-image': 'none',
    'background-color': '#fa7f7f'
});
</script>

app/views/projects/show.html.erb
<div class="container text-center">
	<h3><%= @project.name %></h3>  
	(剩餘天數: <%= @days %> )
</div>
<div class="container">
	<div class="col-md-6 text-center " style ="margin-left: -20px; margin-right: 20px;">
		<% if @photos.present? %>
			<div class="container ">
			  <div id="myCarousel" class="carousel slide" data-ride="carousel" style="width: 50%; ">
			    <!-- Indicators -->
			    <ol class="carousel-indicators">
			      <% @photos.each_with_index do |outing, i| %>
			        <li data-target="#mycarousel" data-slide-to=#{i} class="#{'active' if i == 0}"></li>
			      <% end %>
			    </ol>
			    <!-- Wrapper for slides -->
			    <div class="carousel-inner">
			      <div class="item active">
			        <%= link_to image_tag(@photos.first.image.url(:thumb))%>
			      </div>
			      <% if @photos_count > 1 %>       
			        <% @photos.drop(1).each do |p| %>
			          <div class="item">
			            <%= link_to image_tag(p.image.url(:thumb))%>
			          </div>
			        <% end %>
			      <% end %>      
			    </div>
			  	<!-- Left and right controls -->
			    <a class="left " href="#myCarousel" data-slide="prev">
			      <span class="glyphicon glyphicon-chevron-left"></span>
			    </a>
			    <a class="right " href="#myCarousel" data-slide="next">
			      <span class="glyphicon glyphicon-chevron-right"></span>    
			    </a>
			  </div>
			</div>
		<% end %>
	</div>
	<div class="col-md-6 text-center" style="margin-left: 20px; margin-right: -20px;">
		<p class="strong"><i class="fa fa-calendar" aria-hidden="true"></i>   募資截止日:  <%= @project.due_date%></p>  <br>
	

		<p class="strong"><i class="fa fa-usd " aria-hidden="true"></i>   目標:  NT$<%= @project.total_amount %> </p><br>
		
		<p class="strong"><i class="fa fa-usd " aria-hidden="true"></i>   目前金額:  NT$<%= @project.donation_amount %></p> <br>
		
		<p class="strong"><i class="fa fa-spinner " aria-hidden="true"></i>目前進度: </p>
		<div class="col-md-12 float-right">
		<div class="progress">
	  	<div class="progress-bar pb" role="progressbar" style="width: <%= @progress %>%" aria-valuenow="<% @progress %>" aria-valuemin="0" aria-valuemax="100"><%= @progress %>%</div>
	  </div>
	  </div>

		<% if @project.done == true ||  DateTime.now > @project.due_date  %>
			<%= link_to '已結束募資，回到專案頁面', projects_path ,class:"btn-2nd"%>		
		<% else %>
			<%= link_to '贊助支持', new_project_donation_path(@project),class:"btn-2nd" %>
		<% end %>

	</div>
</div>


<div class=" container text-center project">
	<h3> 專案內容: </h3>
	<p><%= sanitize(@project.content) %></p>
</div>

<div class="container text-center">
	<h4><i class="fa fa-asterisk" aria-hidden="true">故事標題：</i><%= @project.story_title %> </h4>
	<p><%= sanitize(@project.story_content) %></p> 
	
</div>



	

<script>
	$('.pb').css({
    'background-image': 'none',
    'background-color': '#fa7f7f'
});
</script>