config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
	
  resources :stories, only:[:index,:show] , :controller => 'stories' do 
    resources :comments, only:[:create,:destroy], :controller => 'story_comments'
    member do 
      post :like ,:controller => 'stories'
      post :unlike,:controller => 'stories'
    end 

  end

  resources :projects, only:[:index,:show] do #前台只能看index和show頁面
		resources :donations, only:[:show,:new,:create], :controller => 'project_donations' do 
      member do
        post :checkout_pay2go
      end
    end
	end

	root :to =>'stories#index', :controller => 'stories'

  resources :tags, only:[:show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  post 'pay2go/return'
  post 'pay2go/notify'

	namespace :admin do
    resources :stories ,:controller => 'stories' do 
      collection do
        get :home ,:controller => 'stories'
      end
    end
  	resources :projects do #後台CRUD都可
      resources :donation, only:[:index], :controller => 'project_donations'
      resource :report, :controller => 'project_reports'
    end
    
  	resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :tags
	end

  namespace :account do
    resources :stories do 
      collection do
        get :liked
      end
    end
    resources :project_donations
  end

	 #API routes path
  namespace :api, defaults:{ format: :json }do
    namespace :v1 do
      #devise_for :users
      post '/login' => 'auth#login'
      post '/logout' => 'auth#logout'
      resources :users
    end
  end 
  
  

  get '/aboutus', to: 'home#about', :controller => 'home'
  get '/contactus', to: 'home#contact', :controller => 'home'


end

app/models/story.rb
class Story < ApplicationRecord
	has_many :projects
	has_many :story_tags
	has_many :tags, :through => :story_tags
	has_many :photofiles, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :likes
	has_many :users, :through => :likes
	accepts_nested_attributes_for :photofiles,:allow_destroy => true, :reject_if => :all_blank
	validates_presence_of :title, :content, :location, :story_time,:location,:story_time 
	validates :content, length: { minimum: 100 ,too_short: "請至少輸入100字" }

  validates_presence_of :youtube_link, unless: -> { self.photofiles.present? }, :message => "請上傳照片"


	def find_like(user)
		Like.find_by(:story => self, :user => user)
	end

	def already_liked(user)
		find_like(user).present?
	end

	def like_count
		self.likes.count
	end

	def youtube_code		
		self.youtube_link.split("/").last
	end




	

end

app/controllers/account/stories_controller.rb
class Account::StoriesController < ApplicationController
	before_action :authenticate_user!
	before_action :find_story, only:[:show,:edit, :update, :destroy]

	def index 
		@page_title = "我的故事記錄"
		if current_user.role != "admin"
			@stories = Story.where(:author => current_user.name)
		else
			@stories = Story.where(:author => "小編")
		end
	end

	def show 
		@page_title = "故事內容"
		@photos = @story.photofiles
		@photos_count = @photos.count
		if @story.youtube_link.present?
			@link = "https://www.youtube.com/embed/" + @story.youtube_code + "?autoplay=0"
		end
	end

	def new
		@page_title = "新增故事"
		@story = @story = Story.new
		5.times {@photofiles = @story.photofiles.build}
	end

	def create
		@story = Story.new(story_params)	
			if current_user.role != "admin"
				@story.author = current_user.name
			else
				@story.author = "小編"
			end
			if @story.save
				respond_to do |format|
					  format.html { redirect_to account_story_path(@story)}
					  format.js	
					  
				end		
			else 
				5.times {@photofiles = @story.photofiles.build}
				render :new
			end
	end

	def edit
		@page_title = "編輯故事" 
		a = @story.photofiles.count
		b = 5-a
		b.times {@photofiles = @story.photofiles.build}
	end

	def update
		if @story.update(story_params)		
			
			respond_to do |format|
				  format.html { redirect_to account_story_path(@story)}
				  format.js
			end		
		else 
			render :edit
		end
	end


	def destroy 
		@story.destroy
		redirect_to account_stories_path
	end


  def liked
  	@page_title = "我的按讚記錄"
  	@user = current_user
    @likes = Like.where(:user_id => current_user.id)
  end

  protected
  def find_story
		@story = Story.find(params[:id])
	end
	def story_params
		params.require(:story).permit(:story_time,:title,:content,:reflection,
			                          :youtube_link,:is_public,:priority,:location,
			                          :need_project,
			                          :image, :tag_ids => [],
			                          :photofiles_attributes => [:id, :image, :_destroy]
			                          )
	end





end

app/controllers/admin/stories_controller.rb
class Admin::StoriesController < ApplicationController
	layout "admin"
	before_action :check_admin
	before_action :find_story, only:[:show,:edit, :update, :destroy]
	
	def home
		@stories_count = Story.all.count
		@stories_public = Story.where(:is_public => true).count
		@stories_private = @stories_count - @stories_public
		@projects_count = Project.all.count
		@project_public = Project.where(:is_public => true).count
		@projct_private = @projects_count - @project_public
		@users_count = User.where.not(:role => "admin").count
		@reports_count = Report.all.count
		@report_public = Report.where(:is_public => true).count
		@report_private = @reports_count - @report_public

	end

	def index 
		@stories = Story.all

	end

	def show 
		if @story.youtube_link.present?
			@link = "https://www.youtube.com/embed/" + @story.youtube_code + "?autoplay=0"
		end
	end

	def new
		@story = Story.new
		5.times {@photofiles = @story.photofiles.build}

	end

	def create
		@story = Story.new(story_params)	
			if current_user.role != "admin"
				@story.author = current_user.name
			else
				@story.author = "小編"
			end
		if @story.save
			respond_to do |format|
				  format.html { redirect_to admin_story_path(@story)}
				  format.js	
				  
			end		
		else 
			5.times {@photofiles = @story.photofiles.build}
			render :new
		end
	end

	def edit 
		a = @story.photofiles.count
		b = 5-a
		b.times {@photofiles = @story.photofiles.build}
	end

	def update
		if @story.update(story_params)		
			
			respond_to do |format|
				  format.html { redirect_to admin_story_path(@story)}
				  format.js
			end		
		else 
			render :edit
		end
	end


	def destroy 
		@story.destroy
		redirect_to admin_stories_path
	end


	protected

	def find_story
		@story = Story.find(params[:id])
	end

	def story_params
		params.require(:story).permit(:story_time,:title,:content,:reflection,
			                          :youtube_link,:is_public,:priority,:location,
			                          :need_project,
			                          :image, :tag_ids => [],
			                          :photofiles_attributes => [:id, :image, :_destroy]
			                          )
	end

	def check_admin
    unless current_user.role == "admin"
      raise ActiveRecord::RecordNotFound
    end      
  end

 

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_action :authenticate_user!, except:[:index,:show]
	before_action :find_story, except:[:index]
	
	def index
		@page_title = "故事牆" 	
		@top_story =  Story.where(:is_public => true,:priority => true).first
		@stories =  Story.where(:is_public => true, :priority => false).order('created_at desc').page(params[:page]).per(8)
		respond_to do |format|
			format.html {@page_title = "故事牆" }
			format.js
		end	
	end


	def show 
		@page_title = "故事內容"
		@comment_no = @story.comments_count
		@comments = @story.comments.page(params[:page]).per(5)
		if @comments.last_page?
          @next_page = nil
        else
          @next_page = @comments.next_page
        end
        
		@photos = @story.photofiles
		@photos_count = @photos.count
		if @story.youtube_link.present?
			@link = "https://www.youtube.com/embed/" + @story.youtube_code + "?autoplay=0"
		end
		respond_to do |format|
			format.html {@page_title = @story.title }
			format.js
		end		
	end

	def like 	
		unless @story.already_liked(current_user)
			@like = Like.create(:user => current_user, :story => @story)
			redirect_to :back
		end
	
	end

	def unlike
		if @story.already_liked(current_user)
			@like = @story.find_like(current_user)
			@like.destroy
			redirect_to :back
		end
	end

	private

	def find_story
		@story = Story.find(params[:id])
	end

end

app/helpers/account/stories_helper.rb
module Account::StoriesHelper
end

app/helpers/admin/stories_helper.rb
module Admin::StoriesHelper


end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/index.html.erb
<div class=" banner container">
	<%= image_tag "bgc.jpg" ,class:"resize"%>
	<div class="newlayer container text-center ">
			<h3><br><br>TaiwanMega挖掘台灣每個不起眼的小角落故事 <br><br> <strong> <a href="#story">看故事</a> </strong> <br><br></h3>
			
	</div>
</div>
<div class="container text-center" id="story">
	<h1>TaiwanMega說故事</h1>
	 <small>我們挖掘台灣每個不起眼的小角落，讓你知道他們的故事</small> <br><br>
	 <p><i>依分類搜尋:</i>&nbsp;&nbsp;&nbsp;
	<% Tag.all.each do |t| %>
		<i class="fa fa-tag " aria-hidden="true"><%= link_to t.name, tag_path(t.id)%>&nbsp;&nbsp;</i>						
	<% end %>
	</i></p>
</div>

<div class="container text-center">
	<div class="col-md-12">
	<div class="col-md-6">
	<% if @top_story.present? %>
		<%= link_to image_tag(@top_story.photofiles.first.image.url(:medium),class:"top")  %>
	<% end %>
	</div>					
	<div class="col-md-6">
		<h3><%=truncate(@top_story.title, length: 20)%></strong></h3>	

		<i>目前按讚數:<%= @top_story.like_count %></i>
	
		<br>
		<%= sanitize(@top_story.content, :tags=>[]).truncate(200, :separator => " ").html_safe	 %>	<br><br>
		<%= link_to "閱讀更多",story_path(@top_story),class:"btn-2nd" %>	<br><br>	
	</div>
	</div>			
</div>

<div class="container  ">
	<% @stories.each do |s| %>
		<div class="col-md-4">
		
			<div class="col-md-12">
				<%if s.photofiles.present? %>
					<%= link_to image_tag(s.photofiles.first.image.url,class:"story")%>
				<% elsif s.youtube_link.present? %>
					<% @link = "https://www.youtube.com/embed/" + s.youtube_code + "?autoplay=0" %>
					<iframe id="ytplayer" type="text/html"   width="100%" height="200 px" src= "<%= @link %>" frameborder="0"></iframe>
				<% else %>
					<%= image_tag "donation.png",class:"story"%>
				<% end %>
			</div>
			<div class="col-md-12 text-center ">
				<h4><%=truncate(s.title, length: 11)%></h4>
				
				<i>目前按讚數:<%= s.like_count %></i> <br>

	
				<%= sanitize(s.content, :tags=>[]).truncate(90, :separator => " ").html_safe	 %>	<br><br><%= link_to "閱讀更多",story_path(s) ,class:"btn-2nd"%> <br><br>
		
			</div>
		</div>

	<% end %>
	
	<div class="container text-center">
		<%=paginate @stories%>
	</div>
</div>
<div class="container footer text-center">
	<h5>特別感謝</h5>
	<%= image_tag "support.jpg" %>

</div>

<style>
	.story{
		height: 200px;
	}
</style>

app/views/stories/show.html.erb
<div class="container text-center">

  <h1><%=truncate(@story.title, length: 20)%> </h1>
  <h6>作者: <%= @story.try(:author)%></h6>
  <% if @story.tags %>
    <h5><% @story.tags.each do|t| %> 
      <i class="fa fa-tag " aria-hidden="true"><%= t.name %></i>
       <%end%>  
        &nbsp;<i class="fa fa-map-marker" aria-hidden="true"><%= @story.try(:location)%></i>  &nbsp;<i class="fa fa-clock-o" aria-hidden="true"><%= time_ago_in_words(@story.story_time)%></i>
    </h5>
  <% end %>
  <div class="container text-center">
    <%= social_share_button_tag(@story.title) %>
  </div>
  <% if current_user.present? %>
    <% if @story.already_liked(current_user) %>   
      <%= button_to  unlike_story_path(@story), {:remote => true} do %>
          <i class="fa fa-heart fa-2x" aria-hidden="true"><%= @story.like_count %></i>
      <%end %>
    <%else%>      
      <%= button_to like_story_path(@story) , {:remote => true} do%>
        <i class="fa fa-heart-o fa-2x" aria-hidden="true"><%= @story.like_count %>
        </i>
      <%end%>
    <% end %>
  <% else %>
    <i class="fa fa-heart-o fa-2x" aria-hidden="true"><%= @story.like_count %> <small>登入按讚</small>
    </i>
  <% end %>
  <hr class="short">
</div>

<% if @photos.present? %>
<div class="container">

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <% @photos.each_with_index do |outing, i| %>
        <li data-target="#mycarousel" data-slide-to=#{i} class="#{'active' if i == 0}"></li>
      <% end %>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= link_to image_tag(@photos.first.image.url,class:"story")%>
      </div>
      <% if @photos_count >= 1 %>       
        <% @story.photofiles.drop(1).each do |p| %>
          <div class="item">
            <%= link_to image_tag(p.image.url,class:"story")%>
          </div>
        <% end %>
      <% end %>      
    </div>


    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
     
    </a>
  </div>
</div>
</div>
<% else %>
  <div class="container text-center">
  <iframe id="ytplayer" type="text/html" width="100%" height="600" src= "<%= @link %>" frameborder="0"></iframe>
  </div>
<% end %>
<div class="container">
  <h5>內容</h5>
  <p><%= sanitize(@story.content) %></p>
  <h5>反思</h5>
  <p><%= sanitize(@story.try(:reflection)) %></p>
</div>

<div class="container text-center">
  <% if @story.projects.present? %>
    <%= link_to "專案計劃" , project_path(@story.projects.first),class:"btn-2nd"%>
  <% end %>

</div>

<div class="container">   
  <% if current_user %>
  <hr>
    <div class="container">
      <h3>目前:<span id="count"><%= @comment_no %></span> 則留言<i class="fa fa-commenting" aria-hidden="true"></i></h3>
      <%= render :partial => 'story_comments/form' %>
    </div>
      <div class="container" id="comment-list">
        <% @comments.each do |c| %>
          <%= render :partial => 'story_comments/comment', :locals => {:c => c }%>
          
        <% end %>

      </div>

      <% paginate @comments %>

      <div class="container text-center" >
        <% if @next_page %>
          <%= link_to '顯示更多',story_path(@story, :page => @next_page) ,:id => 'load-more',:remote => true %>
        <% end %>
      </div>
<% else %>

  <h3>登入就可觀看留言</h3>
 <% end %>
  <%#= render 'disqus'%>
</div>


<style>
  .carousel {
    width: 100%;
    height: 550px;
  }
  .carousel-inner {
    width: 100%;
    height: 550px;
  }

  .carousel-inner > .item > img, .carousel-inner > .item > a > img {
    display: block;
    max-width: 100%;
    height: 550px;
    line-height: 1;
}

</style>

<script>
  // Load the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/player_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // Replace the 'ytplayer' element with an <iframe> and
  // YouTube player after the API code downloads.
  var player;
  function onYouTubePlayerAPIReady() {
    player = new YT.Player('ytplayer', {
      height: '360',
      width: '640',
      videoId: 'M7lc1UVf-VE'
    });
  }
</script>