config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
	
  resources :stories, only:[:index,:show] , :controller => 'stories' do 
    resources :comments, only:[:create,:destroy], :controller => 'story_comments'
    member do 
      post :like ,:controller => 'stories'
      post :unlike,:controller => 'stories'
    end 

  end

  resources :projects, only:[:index,:show] do #前台只能看index和show頁面
		resources :donations, only:[:show,:new,:create], :controller => 'project_donations' do 
      member do
        post :checkout_pay2go
      end
    end
	end

	root :to =>'stories#index', :controller => 'stories'

  resources :tags, only:[:show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  post 'pay2go/return'
  post 'pay2go/notify'

	namespace :admin do
    resources :stories ,:controller => 'stories' do 
      collection do
        get :home ,:controller => 'stories'
      end
    end
  	resources :projects do #後台CRUD都可
      resources :donation, only:[:index], :controller => 'project_donations'
      resource :report, :controller => 'project_reports'
    end
    
  	resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :tags
	end

  namespace :account do
    resources :stories do 
      collection do
        get :liked
      end
    end
    resources :project_donations
  end

	 #API routes path
  namespace :api, defaults:{ format: :json }do
    namespace :v1 do
      #devise_for :users
      post '/login' => 'auth#login'
      post '/logout' => 'auth#logout'
      resources :users
    end
  end 
  
  

  get '/aboutus', to: 'home#about', :controller => 'home'
  get '/contactus', to: 'home#contact', :controller => 'home'


end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :story_tags
	has_many :stories, :through => :story_tags
	validates_presence_of :name
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
	layout "admin"
	before_action :check_admin
	def index 
		@tags = Tag.all
	end

	
	def create

		@tag= Tag.new(permit_tag)
		if @tag.save
			redirect_to admin_tags_path
		else 
			render :index
		end

	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy
		redirect_to admin_tags_path

	end

	private

	def permit_tag
		params.require(:tag).permit(:name)
	end

	def check_admin
    unless current_user.role == "admin"
    	raise ActiveRecord::RecordNotFound
    end      
  end



end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show 
		@tag = Tag.find(params[:id])
		@stories= @tag.stories.where(:is_public => true)
	end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/show.html.erb
<div class="container text-center">
	<h1><i class="fa fa-tag " aria-hidden="true"><%= @tag.name %></i></h1>
</div>
<div class="container">
		<% Tag.all.each do |t| %>
		   	<i class="fa fa-tag " aria-hidden="true"><%= link_to t.name, tag_path(t.id)%>&nbsp;&nbsp;</i>					
		<% end %>
		<i class="fa fa-tag " aria-hidden="true"><%= link_to "所有", stories_path %></i>
</div>
<div class="container">
	<% @stories.each do |s| %>
		<div class="col-md-3 text-center">
			<table class="table table-bordered">
				<tr><th>故事標題:<%= s.title %></th></tr> 
				<tr><td>時間: <%= s.story_time %></td></tr>
				<tr><td>地點: <%= s.location %></td></tr>
				<tr><td><%= link_to "更多", story_path(s) %></td></tr>
			</table>
		</div>
	<% end %>
</div>
	